server:
  port: 8761
spring:
  profiles: peer1
  application:
    name: eureka-server-peer1
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8769/eureka/,http://127.0.0.1:8770/eureka/
    register-with-eureka: false
    fetch-registry: false
