server:
  port: 8770
spring:
  profiles: peer3
  application:
    name: eureka-server-peer3
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: false
    instance-id: 127.0.0.1:${server.port}:${spring.application.name}
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:8761/eureka/,http://localhost:8769/eureka/
    register-with-eureka: false
    fetch-registry: false
