server:
  port: 8762

spring:
  application:
    name: eureka-client
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: sleuth


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/